### ISSUE TITLE
iOS privacy manifest required

### ISSUE THREAD

**Issue by cokaholic** [MrOlolo/memory_info#5]
I analyzed your repository by using [App Store Privacy Manifest Analyzer](https://github.com/crasowas/app_store_required_privacy_manifest_analyser) and found that you have not added a PrivacyInfo.xcprivacy file, even though there are places where you use the API regarding NSPrivacyAcccessedAPICategoryDiskSpace.

```
Analyzing memory_info-0.0.3 ...
⚠️  Missing privacy manifest file!
API usage analysis result(s): 1
[0] NSPrivacyAccessedAPICategoryDiskSpace:volumeAvailableCapacityForImportantUsageKey,systemFreeSize,systemSize:/Users/a13931/.pub-cache/hosted/pub.dev/memory_info-0.0.3/ios/Classes/MemoryInfo/MemoryInfo.swift
🛠️  Descriptions for the following required API reason(s) may be missing: 1
[0] NSPrivacyAccessedAPICategoryDiskSpace
```

I would like to request the addition of a PrivacyInfo.xcprivacy.

**Comment by cokaholic** [comment]
@MrOlolo 
I have made a pull request to add PrivacyInfo.xcprivacy, so please check it. https://github.com/MrOlolo/memory_info/pull/4

**Comment by MrOlolo** [comment]
Hey! Thanks for pr. Merged and updated. New lib version 0.0.4
